version: '3.7'
services:


  smoke-tests:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile.smoke
    container_name: smoke-tests
    restart: unless-stopped
    env_file:
      - ../env_vars/smoke/dev
      - ../env_vars/smoke/secrets-do-not-commit
    volumes:
      - ..:/app
    ports:
      - 8051:8051
    stdin_open: true
    tty: true
